pipeline {
    agent { label 'JenAgentNode1' }

    environment {
        JAVA_HOME = "/usr/lib/jvm/java-21-openjdk-amd64"
        PATH = "${JAVA_HOME}/bin:${env.PATH}"
    }
    
    options {
        skipStagesAfterUnstable()
    }
    
    stages {
        // stage('Verify Java') {
        //     steps {
        //         sh 'java -version'
        //         sh 'echo $JAVA_HOME'
        //     }
        // }
        // stage('Debug Maven Java') {
        //     steps {
        //         sh 'mvn -v'
        //         sh 'which java'
        //         sh 'which javac'
        //         sh 'echo $JAVA_HOME'
        //     }
        // }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') { 
            steps {
                sh './jenkins/scripts/deliver.sh' 
            }
        }
    }
}
