pipeline {
    agent { label 'JenAgentNode1' }

    environment {
        JAVA_HOME = "/usr/lib/jvm/java-21-openjdk-amd64"
        PATH = "${JAVA_HOME}/bin:${env.PATH}"
    }
    
    options {
        skipStagesAfterUnstable()
    }
    
    stages {
        stage('Verify Java') {
            steps {
                script {
                    if (isUnix()) {
                        sh 'java -version'
                        sh 'echo $JAVA_HOME'
                    } else {
                        bat 'java -version'
                        bat 'echo $JAVA_HOME'
                    }
                }
            }
        }
        stage('Debug Maven Java') {
            steps {
                script {
                    if (isUnix()) {
                        sh 'mvn -v'
                        sh 'which java'
                        sh 'which javac'
                        sh 'echo $JAVA_HOME'
                    } else {
                        bat 'mvn -v'
                        bat 'which java'
                        bat 'which javac'
                        bat 'echo $JAVA_HOME'
                    }
                }
            }
        }
        stage('Build') {
            steps {
                script {
                    if (isUnix()) {
                        sh 'mvn -B -DskipTests clean package'
                    } else {
                        bat 'mvn -B -DskipTests clean package'
                    }
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    if (isUnix()) {
                        sh 'mvn test'
                    } else {
                        bat 'mvn test'
                    }
                }
                post {
                    always {
                        junit 'target/surefire-reports/*.xml'
                    }
                }
            }
        }
        // stage('Deliver') { 
        //     steps {
        //         sh './jenkins/scripts/deliver.sh' 
        //     }
        // }
    }
}
